---
- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    force_apt_get: true
    update_cache: true

- name: Directory for Docker keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Save architecture to variable
  ansible.builtin.set_fact:
    arch: "{{ ansible_architecture }}"

- name: Save codename to variable
  ansible.builtin.set_fact:
    codename: "{{ ansible_distribution_release }}"

- name: Add Docker repository to apt sources
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ codename }} stable"
    state: present
    filename: docker
    update_cache: true

- name: Install docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    force_apt_get: true
    update_cache: true

- name: Docker-Group
  ansible.builtin.group:
    name: docker
    state: present

- name: Docker-Gu
  ansible.builtin.user:
    name: andre
    append: true
    groups: docker
